# Generated by Django 6.0.1 on 2026-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
