# Generated by Django 6.0.1 on 2026-01-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_goal_completed_at_goal_completion_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('WINDOWED', 'Windowed (N in M days)')], default='DAILY', max_length=10),
        ),
    ]
