# Generated by Django 6.0.1 on 2026-01-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_frequency_config_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalprogress',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='goalprogress',
            unique_together=set(),
        ),
    ]
