# Generated by Django 6.0.1 on 2026-01-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_goalprogress_source_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalprogress',
            name='source_habit',
        ),
    ]
