# Generated by Django 6.0.1 on 2026-01-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_goalprogress_source_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalprogress',
            name='source_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_progress', to='tracker.habit'),
        ),
    ]
