# Generated by Django 6.0.1 on 2026-01-20 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0007_goalprogress_source_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overview', models.TextField()),
                ('patterns', models.JSONField(default=list)),
                ('reflection', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='tracker.goal')),
            ],
        ),
    ]
